#!bin/sh

# altering cd
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# specific folders to me
alias def="cd ~/def && exa -lah"
alias scripts="cd ~/def/scripts/ && exa -lah"
alias docs="cd ~/def/docs && exa -lah"
alias pics="cd ~/def/docs/Picturesd && exa -lah"
alias videos="cd ~/def/docs/Videos && exa -lah"
alias downloads="cd ~/def/docs/Downloads && exa -lah"
alias dox="cd ~/def/docs/Documents/ && exa -lah"
alias cfgrepo="cd ~/def/cfgrepo && exa -lah"
alias aliases="cd ~/def/dotfiles/shell/aliases && exa -lah"
alias dotfiles="cd ~/def/dotfiles/ && exa -lah"
alias repos="cd ~/def/repos && exa -lah"
alias books="cd ~/def/docs/Documents/books && exa -lah"
alias tutorials="cd ~/def/repos/tutorials/&& exa -lah"
alias projects="cd ~/def/repos/projects && exa -lah"
alias pubscripts="cd ~/def/scripts/pub && exa -lah"
alias privscripts="cd ~/def/scripts/_priv/ && exa -lah"
alias BIT="cd ~/def/repos/BIT/certificate/ && exa -lah"
alias BIT-501="cd ~/def/repos/BIT/certificate/BIT-501-Business-Concepts-and-Communication/ && exa -lah"
alias BIT-502="cd ~/def/repos/BIT/certificate/BIT-502-Fundamentals-Of-Programming/ && exa -lah"
alias BIT-503="cd ~/def/repos/BIT/certificate/BIT-503-Fundamentals-of-Information-Technology/ && exa -lah"
alias code-bit="cd /home/naturalhacks/def/repos/BIT/certificate/BIT-502-Fundamentals-Of-Programming/BIT-502-Code && exa -lah"
alias fund-bit="cd /home/naturalhacks/def/repos/BIT/certificate/BIT-503-Fundamentals-of-Information-Technology/ && exa -lah"
alias notes="cd /home/naturalhacks/def/docs/Documents/notes && exa -lah"
alias p-notes="cd /home/naturalhacks/def/docs/Documents/notes/programming/ && nvim ."
